### ISSUE TITLE
[100 SigmaUSD] Pass a tx fee parameter instead of hardcoded `BoxValue::SAFE_USER_MIN`

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#101]
Use the value from `OracleConfig::base_fee`.

**Comment by hanbu97** [comment]
I did some attempt. [https://github.com/ergoplatform/oracle-core/commit/4ecec26754230f8080fc16ebca3b5803c886ff50](url)

But in this way did nothing help to change the default SAFE_USER_MIN inside reference functions from other crates.

**Comment by greenhat** [comment]
> I did some attempt. [https://github.com/ergoplatform/oracle-core/commit/4ecec26754230f8080fc16ebca3b5803c886ff50](url)

Great! Thank you! The problem with making the fee lazy static and loading it from the config file is that most of our tests should fail due to missing config file. I was thinking of passing the tx fee as the argument to the functions where it's needed.

> But in this way did nothing help to change the default SAFE_USER_MIN inside reference functions from other crates.
Could you give an example of such a function? I cannot recall any from the top of my head.

**Comment by hanbu97** [comment]
How about giving a default value if comfig file does not exist.

**Comment by greenhat** [comment]
Good idea!

**Comment by hanbu97** [comment]
Is this works?
``` rust
    - pub static ref SAFE_USER_MIN: BoxValue = BoxValue::try_from(ORACLE_CONFIG.base_fee).unwrap();
    + pub static ref SAFE_USER_MIN: BoxValue = MAYBE_ORACLE_CONFIG
    +    .as_ref()
    +    .map(|c| BoxValue::try_from(c.base_fee).unwrap())
    +    .unwrap_or(BoxValue::SAFE_USER_MIN);
```
[https://github.com/ergoplatform/oracle-core/commit/53e53ce545a367ed67789f0768ed859009d5e133](url)

**Comment by greenhat** [comment]
Yes. It looks good.

**Comment by hanbu97** [comment]
I made a PR. Please check it.

**Comment by greenhat** [comment]
Done in #104.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
