### ISSUE TITLE
[100 SigmaUSD] Ensure that in `*ContractParameters::p2s` is always in sync with other parameter values 

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#107]
The goal is to make invalid `*ContractParameters` instances unrepresentable. In invalid instances, constant values in `p2s` are not the same as in the `*ContractParameters` properties.
One option to ensure this would be to go down the same route I took in https://github.com/ergoplatform/oracle-core/pull/95 with `*ContractInputs`, making one property private and introducing two constructors: `load` (checks that `p2s` has the same values) and `create` (substitutes constant values in `p2s` with `*ContractParameter` properties).

**Comment by kettlebell** [comment]
I'll work on this.

**Comment by greenhat** [comment]
Great! I forgot to mention, that it should be done after #95 is merged.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
