### ISSUE TITLE
[200 SigmaUSD] Update registered scans and re-scan the wallet after UpdatePool command

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#110]
Discovered in https://github.com/ergoplatform/oracle-core/pull/109#discussion_r968025042

Since we need to do this on every oracle after they receive a new config, I think we need to check if existing scans reference a changed token id/address/etc. and only then update the scanids.json and trigger a wallet re-scan.

**Comment by kettlebell** [comment]
I will work on this.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
