### ISSUE TITLE
[500 SigmaUSD] Implement submit data point operation 

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#16]
Remove existing separate [app](https://github.com/ergoplatform/oracle-core/blob/e2509db95d1b93c9800a8743e0c301ebddf89afb/connectors/erg-usd-connector/src/main.rs#L35-L45) which submits data points to the oracle main app via [REST API](https://github.com/ergoplatform/oracle-core/blob/e2509db95d1b93c9800a8743e0c301ebddf89afb/core/src/api.rs#L17)

Implement data point submission according to [EIP-23](https://github.com/ergoplatform/eips/blob/eip23/eip-0023.md#publish-data-point) in the oracle main app in the main event loop using process-build_action-execute_action workflow (see `PoolCommand::Refresh` and `PoolAction::Refresh` for examples).

The overall design should accommodate using an alternative custom data point source by running the shell command provided via the config file option (which can be hard-coded for now).

### References
EIP-23 - https://github.com/ergoplatform/eips/blob/eip23/eip-0023.md
Contracts and tests - https://github.com/scalahub/OraclePool

**Comment by kettlebell** [comment]
Will work on this.

**Comment by greenhat** [comment]
> > The overall design should accommodate using an alternative custom data point source by running the shell command provided via the config file option (which can be hard-coded for now).
> 
> So my idea for this is to allow for communication with a local CLI app that provides the data point. We can be flexible, allowing for oracle-core to:
> 
> * spawn the app as a child-process, communicating with the parent via unix socket or TCP-through-localhost e.g. `oracle-core --spawn-data-point-source-app path/to/app --tcp --port 1234`
> * allow user to run the app separately

I thought about something much much more simpler. :) See my explanation below.
 
> We can also do what's described here in [connector-lib](https://github.com/ergoplatform/oracle-core/tree/develop/connectors/connector-lib#advanced-usage)
> 
> Also, do you ultimately want to delete the code in `connectors/`?

My idea was to radically simplify the design and to go with one app. Current two app design makes every aspect of oracle pools more complex (distribution, setup, monitoring) without current operators benefiting from it all that much. If we "hard-code"(via funtion/trait/etc.) the current data point fetching into the oracle app itself and give to operators an option to call aribtrary shell script that would be a win-win for everybody. The arbitraty shell script is expected to print the data point(rate) in the stdout and we parse it. Most operators are running the default rate fetching and the ones that want customization will do it via their own shell/tool.
So, yes, the `connector-*` hierarchy can be deleted.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
