### ISSUE TITLE
Bootstrap the oracle pool command

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#17]
The goal is to automate the whole bootstrap process for the new oracle pool and run it with a single command.

Run bootstrap via a command-line option and a special config file with
bootstrap parameters "--bootstrap bootstrap_config.yaml".

In the bootstrap_config.yaml the following parameters are required:
- token names and quantities https://github.com/ergoplatform/eips/blob/eip23/eip-0023.md#tokens;

The bootstrap process mints:
- pool NFT token;
- refresh NFT token;
- oracle tokens;
- reward tokens;

and creates [pool and refresh
boxes](https://github.com/ergoplatform/eips/blob/eip23/eip-0023.md#boxes) via
chained transactions (inputs for the subsequent transactions are outputs of
the previous transactions in the mempool) in one block. The contracts should
be constructed from the contracts defined in the `contracts` module with minted tokens via [`with*`](https://github.com/ergoplatform/oracle-core/blob/2c56d1f1dc1eb2cc602400f83aa5c906c4cabb4f/core/src/contracts/refresh.rs#L127) calls.

Oracle tokens should be put in a box guarded by the node wallet's PK for distribution among the oracles later.

The bootstrap process also generates an output config file to run the oracle
pools app. In the output config file the following info should be present:
- minted token IDs

**Comment by kettlebell** [comment]
Working on this as part of Ergohack.
