### ISSUE TITLE
[100 SigmaUSD] Add ERG/BTC data point source

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#191]
It'd be great if we have some redundancy and get it from more than one source. Check out existing ERG/USD and ERG/XAU  sources for a redundancy example.

**Comment by sethdusek** [comment]
I will work on this

**Comment by greenhat** [comment]
Done in https://github.com/ergoplatform/oracle-core/pull/304 
The bounty is sent. Thank you!
