### ISSUE TITLE
[200 SigmaUSD] Build the binary and publish it as a release artifact via CI

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#22]
We'd want to have binaries available to download from the github's release page for Linux, macOS, and ideally Windows.
The build should be triggered when a github's release is created.

EDIT:
To support old GLIBC versions starting from RHEL 8 which has 2.28 let's try building on the `ubuntu-20.04` image (see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) on GA.
Here is an explanation of why GLIBC version matters in static binary build - https://www.reddit.com/r/rust/comments/n6udyk/building_rust_binaries_in_ci_that_work_with_older/

**Comment by kettlebell** [comment]
Starting on this.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
