### ISSUE TITLE
Systemd compatibility

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#23]
Adapt the app to be launched as daemon under systemd.
To check:
- output, logging;
- signal handling;

**Comment by kettlebell** [comment]
What do you think about providing a template systemd service file `oracle-pool.service` for a user to put under `/etc/systemd/system'? All they would need to do is set the location of the binary and config, modify the service file then off it goes.

We can go even further and lockdown the service with separate user/group, read-only home directory etc.

**Comment by greenhat** [comment]
> What do you think about providing a template systemd service file `oracle-pool.service` for a user to put under `/etc/systemd/system`? All they would need to do is set the location of the binary and config, modify the service file then off it goes.

Good call! I was thinking of writing a script that installs systemd service, but with all edge cases handling and different requirements from users, it's way too complex. The template might be a great middle-ground. I made #33.
 
> We can go even further and lockdown the service with a separate user/group, read-only home directory, etc.

That is when it gets tricky. Like if you run it in the container you don't need a separate user, etc.

**Comment by kettlebell** [comment]
> That is when it gets tricky. Like if you run it in the container you don't need a separate user, etc.

If we provide a docker image, I believe we can skip systemd altogether. Docker containers have good support for signal handling and many options for security. The images will be very compact too, since it's just a single binary on top of a thin base (probably Alpine Linux). I think we can also give users this option, what do you think?

**Comment by greenhat** [comment]
> > That is when it gets tricky. Like if you run it in the container you don't need a separate user, etc.
> 
> If we provide a docker image, I believe we can skip systemd altogether. Docker containers have good support for signal handling and many options for security. The images will be very compact too, since it's just a single binary on top of a thin base (probably Alpine Linux). I think we can also give users this option, what do you think?

Sure, we can provide this option. I'm not sure we make it primary though. For a single static binary dependent on an externally running node this looks like an overkill. Plus, we will have commands (extract rewards, voting, etc.) which container makes a bit harder to run.

**Comment by kettlebell** [comment]
Oh yeah, I didn't think about the commands.
