### ISSUE TITLE
Add CLI switch to auto approve "extract-reward-tokens" command

### ISSUE THREAD

**Issue by spireblockchain** [ergoplatform/oracle-core#315]
As the summary states, can a switch be added to the oracle-core "extract-reward-tokens" command so that reward tokens can be claimed automatically via script?

**Comment by greenhat** [comment]
I tested `./oracle-core extract-reward-tokens ADR <<< 'YES'`, and it works. Would it be sufficient?

**Comment by spireblockchain** [comment]
The goal is to automate reward claiming, so this solution works.  Appreciate it!
