### ISSUE TITLE
Add scan start blockheight parameter in config

### ISSUE THREAD

**Issue by mgpai22** [ergoplatform/oracle-core#319]
It seems like rescan starts from block 0

- As found [here](https://github.com/ergoplatform/oracle-core/blob/1321adb9a698a4d444adf59384d288583402eca2/core/src/scans/registry.rs#L90) and [here](https://github.com/ergoplatform/oracle-core/blob/1321adb9a698a4d444adf59384d288583402eca2/core/src/scans/registry.rs#L119)
- These scans are expensive and wastes plenty of time, its best to start from a checkpoint height where bootstrapping and whatnot begins.
- This checkpoint height should be in the `oracle_config.yaml` file

**Comment by greenhat** [comment]
We did that initially, but it did not work. Since the wallet does not see anything before this height, you end up with an empty wallet if you sent coins to it before this height.

**Comment by mgpai22** [comment]
Yes that's why it should be configurable in the `oracle_config.yaml` file
