### ISSUE TITLE
Remove side-effects from `main`

### ISSUE THREAD

**Issue by kettlebell** [ergoplatform/oracle-core#40]
Currently the main function is bloating up due to side effects from CLI commands. Refactor it to have a similar workflow to pool commands.

**Comment by kettlebell** [comment]
Hi @greenhat just continuing from your comment in https://github.com/ergoplatform/oracle-core/pull/36#pullrequestreview-987141523, the bootstrap code under the `cli_commands` module actually has a mix of both business-logic and side-effects, since it submits all the transactions to the mempool at the end. I think it's ok since the entire bootstrap processed in bound within that single file.

I plan to do a similar thing for extract/print rewards. I can definitely get the side effects out of `main`.

**Comment by greenhat** [comment]
> Hi @greenhat just continuing from your comment in [#36 (review)](https://github.com/ergoplatform/oracle-core/pull/36#pullrequestreview-987141523), the bootstrap code under the `cli_commands` module actually has a mix of both business-logic and side-effects, since it submits all the transactions to the mempool at the end. I think it's ok since the entire bootstrap processed in bound within that single file.
> 
> I plan to do a similar thing for extract/print rewards. I can definitely get the side effects out of `main`.

Sounds great!
