### ISSUE TITLE
Get working pool on testnet

### ISSUE THREAD

**Issue by kettlebell** [ergoplatform/oracle-core#42]
Hi @greenhat I've got an ergo node on testnet running and have been trying to get oracle bootstrap happening (there are a bunch of bugs on `develop` branch that I will fix in upcoming commits). But I immediately have a problem when trying to sign the first transaction by the node for minting the first token.

Using the `wallet/transaction/sign` endpoint, JSON payload for the `UnsignedTransaction` is:
```json
{
  "inputs": [
    {
      "boxId": "4bdd60da23c2dcbb347626845ac66b3a92297273022ed3c93d61b4e0f5a2ec66",
      "extension": {}
    }
  ],
  "dataInputs": [],
  "outputs": [
    {
      "value": 1000000,
      "ergoTree": "0008cd030458fff90453884bec45858745be6d48748ceb4559944f996fbc67a7ebb81189",
      "assets": [
        {
          "tokenId": "4bdd60da23c2dcbb347626845ac66b3a92297273022ed3c93d61b4e0f5a2ec66",
          "amount": 1
        }
      ],
      "additionalRegisters": {
        "R4": "0e134552472f555344204f5020706f6f6c204e4654",
        "R5": "0e134552472f555344204f5020506f6f6c204e4654",
        "R6": "0e0131"
      },
      "creationHeight": 235914
    },
    {
      "value": 14000000,
      "ergoTree": "0008cd030458fff90453884bec45858745be6d48748ceb4559944f996fbc67a7ebb81189",
      "assets": null,
      "additionalRegisters": {},
      "creationHeight": 235914
    },
    {
      "value": 59984000000,
      "ergoTree": "0008cd02428fbf621f43617dbb2b949427f7ef888003b9f83c741bbf971ddb48182bc8e0",
      "assets": null,
      "additionalRegisters": {},
      "creationHeight": 235914
    },
    {
      "value": 1000000,
      "ergoTree": "1005040004000e36100204a00b08cd0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798ea02d192a39a8cc7a701730073011001020402d19683030193a38cc7b2a57300000193c2b2a57301007473027303830108cdeeac93b1a57304",
      "assets": null,
      "additionalRegisters": {},
      "creationHeight": 235914
    }
  ]
}
```
Note that the existing code wraps up the transaction with
```json
{ 
  "tx": "...json above"
}
```

Now the node rejects this request with the following error message:
```
Node Response: The request content was malformed:
C[A]: DownField(assets),MoveRight,DownArray,DownField(outputs),DownField(tx)
```

Now it looks to me that the problem is with the `assets` field under `tx.outputs[1]`. Any idea what's going on?

**Comment by kettlebell** [comment]
I think in scala, the ergo node treats the tokens as a `Coll`, which can be empty (https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c59139b3e5718362937817f42302b86dc2174f58/sigmastate/src/main/scala/org/ergoplatform/ErgoBox.scala#L54)? Whereas in `sigma-rust`, `ErgoBoxCandidate::tokens` is of type `Option<BoundedVec<1,255..>>`, so no tokens means this field is `None`, which is encoded as `null` in JSON.

**Comment by greenhat** [comment]
Yes, `null` vs `[]` is the first thing that caught my eye. Besides that, the node is expecting tokens encoded as tuples - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c59139b3e5718362937817f42302b86dc2174f58/sigmastate/src/main/scala/org/ergoplatform/JsonCodecs.scala#L355

I'm going to fix it ASAP.

**Comment by greenhat** [comment]
Ha! After all, a token tuple is encoded as a dictionary - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c59139b3e5718362937817f42302b86dc2174f58/sigmastate/src/main/scala/org/ergoplatform/JsonCodecs.scala#L79-L91
So, it's only `null` vs `[]` then.

**Comment by kettlebell** [comment]
Close since more progress described in #61
