### ISSUE TITLE
[800 SigmaUSD] Update pool box command

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#49]
Should be done after #26 and after #51

As per https://github.com/ergoplatform/eips/blob/bd7a6098db78d67ac2ca9ada4c09bfe709d5ac03/eip-0023.md#update-pool-box (with updates introduced in [v2.0a](https://github.com/scalahub/OraclePool/tree/v2/src/main/scala/oraclepool/v2a), e.g reward tokens were moved from the refresh box to the pool box)) add a command line option `--update-pool-box` with the following parameters:
- new pool box hash;
- height on which the new update box should be created(exit if not the current height);

**Comment by SethDusek** [comment]
I'd like to do this one. One more question by the way:

> new pool box hash

Would the new Pool Contract be a P2SH address then? Should we instead pass a serialized ErgoTree, because if I understand it correctly, then everyone interacting with the contract would now have to provide the script that hashes to the address as well.

**Comment by greenhat** [comment]
No, it supposed to be P2S. 
I don't think we could handle the provisioning of an arbitrary pool box contact in runtime. We need to support it in the PoolContract, thus issuing a new app build/version. So we only need a hash as a check that we're area going to deploy there right contact.

**Comment by SethDusek** [comment]
Hmm alright, but for changing pool parameters, like [epoch length, reward tokens, etc](https://github.com/ergoplatform/eips/blob/bd7a6098db78d67ac2ca9ada4c09bfe709d5ac03/eip-0023.md#update-rules) would the right way to do it be to have another update/configuration file, where a user can pass new RefreshContractParameters/NftMintDetails/etc? I don't think we would need an oracle-core update to change those parameters

**Comment by greenhat** [comment]
Excellent question!
In that case we would not be able to encode the contract preservation clause in the contract itself, i.e. ensure that the contract in the output box is the same as in the box being spent.

**Comment by greenhat** [comment]
Oh, I think I misread it. In case you're talking of the implementation, then yes, eventually we will have contact structure(contacted indices) in the config file and will be able to change it without recompilation.

**Comment by greenhat** [comment]
The bounty is increased due to the extended scope of #80.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
