### ISSUE TITLE
[100 SigmaUSD] Minted update NFT should be locked in update box on bootstrap

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#50]
After #51

On bootstrap op the minted update NFT should be placed in the update box locked with update contract https://github.com/ergoplatform/eips/blob/bd7a6098db78d67ac2ca9ada4c09bfe709d5ac03/eip-0023.md#update-contract
Otherwise, a token holder would be able to singlehandedly change the pool box (see pool contract https://github.com/ergoplatform/eips/blob/bd7a6098db78d67ac2ca9ada4c09bfe709d5ac03/eip-0023.md#pool-contract)

**Comment by SethDusek** [comment]
I'd like to attempt this one

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
