### ISSUE TITLE
[200 SigmaUSD] Add `contracts::update` module with update contract implemented

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#51]
See contract source - https://github.com/ergoplatform/eips/blob/bd7a6098db78d67ac2ca9ada4c09bfe709d5ac03/eip-0023.md#update-contract with updates introduced in [v2.0a](https://github.com/scalahub/OraclePool/tree/v2/src/main/scala/oraclepool/v2a), e.g reward tokens were moved from the refresh box to the pool box

For example see how other contracts `contracts::*` are implemented.

**Comment by SethDusek** [comment]
I'd like to take this one

**Comment by greenhat** [comment]
Done in #60. Bounty is sent.
