### ISSUE TITLE
[100 SigmaUSD] Add ERG/XAU pair datapoint source

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#54]
Coingecko API should be able to show ERG in XAU prices. See discord - https://discord.com/channels/668903786361651200/669989266478202917/986627954568204320

See the existing NanoErgUsd datapoint source as an example - https://github.com/ergoplatform/oracle-core/blob/fcffd8a1c22900f99511d25f22e1b34ef0fdaf80/core/src/datapoint_source/erg_usd.rs#L8-L32

Add new datapoint source handling in the oracle config load - https://github.com/ergoplatform/oracle-core/blob/fcffd8a1c22900f99511d25f22e1b34ef0fdaf80/core/src/oracle_config.rs#L52-L56

**Comment by kettlebell** [comment]
I'll do this.
