### ISSUE TITLE
[100 SigmaUSD] Consider using `serde_yaml` for `BootstrapConfig` parsing and serialization

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#65]
Instead of `bootstrap_config_from_yaml` use `serde_yaml` for YAML parsing.
Also, get serialization "for free" to provide the end-user with generated bootstrap config example (like `bootstrap dump-config` command). This way we avoid the need to ship the bootstrap config example externally.

**Comment by greenhat** [comment]
@kettlebell What do you think?

**Comment by kettlebell** [comment]
Yes, we definitely can. Would you like me to take this issue on?

**Comment by greenhat** [comment]
It'd be great! But it's not a high priority, so no rush.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
