### ISSUE TITLE
Consider avoiding `with_...` call chains to build a contract

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#72]
### Motivation
Builder pattern for contracts might be a bad idea. We might end up with a partially updated contract if some call to `with...` is missed. I have not yet seen a case where we need to update only one parameter of the contract.

### Implementation details
A simple c'tor with required parameters might be a better option than a builder pattern.
Don't rely on `ORACLE_CONFIG`. I suspect we might get rid of it since we might need to mock some options in tests.

**Comment by greenhat** [comment]
> I agree with you and I'm doing this already as part of #30. For example I have this:
> 
> ```rust
> pub struct OracleContractParameters {
>     pub p2s: String,
>     pub pool_nft_index: usize,
>     pub pool_nft_token_id: TokenId,
> }
> ```
> 
> with the constructor for the `OracleContract` looking like `pub fn new(parameters: &OracleContractParameters) -> Self`
> 
> It's easy to mock `OracleContractParameters` and we can also add it as a field to the `OracleConfig` struct.

Looks interesting! Do you find making a separate struct for parameters vs. function arguments beneficial for only three parameters? I mean I see the value of named parameters, but I'd reach for the separate struct when I have a lot of arguments. Although I like using it as a field in `OracleConfig`. I might've answered my question already. :)

BTW, we have `NetworkAddress` which might be a better fit for `p2s` than `String`.

**Comment by kettlebell** [comment]
> BTW, we have `NetworkAddress` which might be a better fit for `p2s` than `String`.

Thanks for the tip!

**Comment by greenhat** [comment]
> Yes, in addition to being fields in `OracleConfig` we need to modify the impls for `*BoxSource` traits, since the contract parameters are now external to the app. Need to do as follows:
> 
> ```rust
> impl LocalDatapointBoxSource for (Scan, OracleContractParameters) {
>     fn get_local_oracle_datapoint_box(&self) -> Result<OracleBoxWrapper> {
>         let box_wrapper = OracleBoxWrapper::new(self.0.get_box()?, &self.1)?;
>         Ok(box_wrapper)
>     }
> }
> ```

I don't get why the box wrapper gets the contract in ctor parameter? It should be parsed from the box. As long as the constant indices are hardcoded.
Oh, I see. The constant indices are also in `*ContractParameters`, right?

**Comment by ross-weir** [comment]
Just to add, I think that's why a separate struct like `ContractBuilder` would usually be used to return the built `Contract` struct - so it can validate the state and ensure the built object is valid

**Comment by greenhat** [comment]
> Just to add, I think that's why a separate struct like `ContractBuilder` would usually be used to return the built `Contract` struct - so it can validate the state and ensure the built object is valid

Good point! But with contracts, we tend to set all available parameters at once rather than updating only a few of them and leaving the rest "default"(parsed from P2S). I think of it as filling the template where all "holes" should be filled. And since there are not many of them, a constructor might be a better fit.
