### ISSUE TITLE
Consider updating ergo-node-interface

### ISSUE THREAD

**Issue by SethDusek** [ergoplatform/oracle-core#74]
Hi, working on getting pool setup on testnet, and I was unable to start the bootstrap process. It keeps erroring with the following:

>Node Response: The request content was malformed:
>String: DownArray,DownField(inputsRaw)

After some testing, it appears that the serialization of UnsignedTransaction in the current ergo-node-interface is the issue:

```rust
       let endpoint = "/wallet/transaction/sign";
       let prepared_body = json!({ "tx": unsigned_tx, "inputsRaw": boxes_to_spend, "dataInputsRaw": data_input_boxes });
```
Comparing this to the serialization of UnsignedTransaction in ergo-lib, it seems the correct field is inputs and not inputsRaw, since that seems to be a different format (boxes are serialized and not in JSON form). Newer versions of ergo-node-interface fix this. I can send a PR to update it if you wish

**Comment by greenhat** [comment]
Good catch! I'm also testing bootstrap on the testnet. I fixed it in https://github.com/ergoplatform/ergo-node-interface-rust/pull/11 and will merge it ASAP. What newer versions do you mean?

**Comment by greenhat** [comment]
If by the newer version you mean my PR, then yes, please send a PR to update it here in develop branch.

**Comment by SethDusek** [comment]
I believe latest develop branch does not have this issue, while the one oracle-core has pinned to has the outdated serialization. I'm currently working on an update.

I ran into some additional issues in the bootstrap phase. I'll try to take a look at those as well

**Comment by greenhat** [comment]
> I believe latest develop branch (ergo-node-interface) does not have this issue, while the one oracle-core has pinned to has the outdated serialization. 

That's weird. I'm sure it's only fixed in my PR.

> I'm currently working on an update.
> 
> I ran into some additional issues in the bootstrap phase. I'll try to take a look at those as well

Great! I'm documenting my progress in https://github.com/ergoplatform/oracle-core/issues/61 in comments.

> 
> Currently running into this after getting the previous issue fixed:
> 
> > 2022-07-05T10:57:40.963260355+05:00 INFO oracle_core::cli_commands::bootstrap - bootstrap.yaml loaded
> > 2022-07-05T10:57:40.989778157+05:00 INFO oracle_core::cli_commands::bootstrap - Minting pool NFT tx
> > 2022-07-05T10:57:41.022960102+05:00 INFO oracle_core::cli_commands::bootstrap - Minting refresh NFT tx
> > 2022-07-05T10:57:41.039046012+05:00 ERROR oracle_core - Fatal bootstrap error: node error: The node rejected the request you provided.
> 
> I think the issue might be that each step in the bootstrap process uses the UTXOs created by the previous transaction, but those transactions haven't actually been submitted yet, so the node rejects that transaction? If my understanding of the issue is correct, is there any way to build a chained transaction?

That's where I'm stuck now as well. Chained tx should work if the inputs are in mempool. Here is the test for this in node - https://github.com/ergoplatform/ergo/blob/205eabf79806b428f86d4b8c866b4df0581b9458/src/test/scala/org/ergoplatform/http/routes/TransactionApiRouteSpec.scala#L64-L78

**Comment by greenhat** [comment]
Wait, I forgot I have https://github.com/ergoplatform/oracle-core/pull/71 
I'm going to merge it ASAP.
