### ISSUE TITLE
Display Token IDs/Parameters of Oracle Pool after Bootstrap

### ISSUE THREAD

**Issue by SethDusek** [ergoplatform/oracle-core#79]
Hi, after a successful bootstrap, it would be great if all of the Token IDs could be displayed, ideally in the same format as oracle_config.yaml, so that parameters can be easily copied into the oracle_config file. Right now you need to open explorer with the Transaction IDs and copy the token parameters from there. 

I can assign myself to this issue if you think this would be a worthwhile addition

**Comment by kettlebell** [comment]
Also there will be many changes to the YAML file once https://github.com/ergoplatform/oracle-core/pull/75 is complete. I'll make sure the YAML files are consistent too.

**Comment by SethDusek** [comment]
Ah, I missed that, I was looking at the bootstrap_chained_transaction code.
