### ISSUE TITLE
[100 SigmaUSD] Return `EcPoint` instead of `ProveDlog` in box wrapper methods.

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#81]
To avoid issues described in https://github.com/ergoplatform/oracle-core/pull/80#discussion_r928101909

**Comment by ApexTheory** [comment]
Hey @greenhat! I can pick up this one.

**Comment by SethDusek** [comment]
Hi @ApexTheory are you still working on this? If not, can I pick it up?

**Comment by ApexTheory** [comment]
Hi @SethDusek all yours

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
