### ISSUE TITLE
[300 SigmaUSD] Rescan blocks after registering set-scans

### ISSUE THREAD

**Issue by SethDusek** [ergoplatform/oracle-core#85]
Hi, while doing some testnet runs, I noticed that after registering the scans, you have to use the node interface to rescan. Ideally oracle-core should maybe call the rescan endpoint itself. However, we would need some way to store the height of the bootstrap transaction(s), because rescanning from height 0 can be quite time consuming

Maybe bootstrap should store "creation_height" as a temporary file, and when oracle-core run/OraclePool::new() is called, it should check that file and rescan from there after registering scans.

**Comment by greenhat** [comment]
It'd be great if the oracle app asked a node for rescan! We should not save the blockchain height in bootstrap, though. Joined oracles need to rescan the wallet too. Maybe we should check a temp file with stored height on every app launch and run a rescan if a temp file is not found from the current height. Or do we need to run the rescan exactly from the bootstrap height?

**Comment by SethDusek** [comment]
Once a scan is registered, it will scan all new blocks, but it's not retroactive. So I think we only need the temp file for the first time we register scans

**Comment by greenhat** [comment]
Yes, I meant to run rescan only once when there is no temp file. What if we run a rescan for current height - 50 deep on the first app launch? That should catch a pool and other boxes, right? Heck, we could do 1000 instead of 50 if needed.

**Comment by SethDusek** [comment]
Hmm, 1000 is a pretty safe margin for mainnet. I think it's a good solution

**Comment by SethDusek** [comment]
I will work on this

**Comment by SethDusek** [comment]
Hmm, after some more thought, I think one way might be to store creation height of pool box in oracle_config.yaml as an optional parameter. The benefit of this would be that someone who's joining the oracle pool could copy the pre-filled configuration file for a pool, and that'd include the height needed to rescan.

**Comment by greenhat** [comment]
@SethDusek You're right. I forgot about the Update box. I think we should make rescan height a mandatory parameter in the config file. Since the fallback would be to scan from the genesis, and this takes ages. 
I'm revamping the bootstrap to generate the whole config file here - https://github.com/ergoplatform/oracle-core/pull/95 and I can add rescan_height parameter.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
