### ISSUE TITLE
[50 SigmaUSD] Remove node's address conversion

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#86]
Namely https://github.com/ergoplatform/oracle-core/blob/b852636b7828e7f5b732b2c508081838e27f321a/core/src/node_interface.rs#L114-L145
Replace any used functions with local implementation.

**Comment by SethDusek** [comment]
I will work on this

**Comment by greenhat** [comment]
I've underestimated this task initially. The bounty is increased.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
