### ISSUE TITLE
[300 SigmaUSD] Network agnostic-ness

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#88]
It should be done after #80 is merged.

I've looked through the code and did not find a reason to distinguish between mainnet and testnet. 

Implementation details.
Use network-agnostic `Address` for `*ContractParameters::p2s`. Parse base58 address with `Address::unchecked_parse_from_str()`.
~~Contracts in conf files should be encoded as base16 serialized bytes (node/explorer format).~~

EDIT: We probably should leave contracts as P2S strings in conf files. To be able to use plutomonkey for contract compilation.

**Comment by kettlebell** [comment]
I'll get onto this.
