### ISSUE TITLE
[100 SigmaUSD] `OraclePool` should only be instantiated once and passed to the users

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#97]
To avoid https://github.com/ergoplatform/oracle-core/pull/96.
Plus, there is no real need for all interested parties to have their instance.

**Comment by greenhat** [comment]
Also, not all users need the whole `OraclePool` struct. If only one or two properties are used, consider passing them instead.

**Comment by greenhat** [comment]
I thought about lazy_static, but I see it as a sort of "last resort". I mean it's essentially an immutable global var, which we cannot mock in tests. I'd prefer passing an instance as a parameter and if it gets too ugly, make it a lazy_static.

**Comment by hanbu97** [comment]
Do we need implement Sync for OraclePool first?

**Comment by greenhat** [comment]
> Do we need implement Sync for OraclePool first?

Good question. I'd keep it as simple as possible. If it becomes too much of a hassle, we can pass only needed fields as arguments.

**Comment by hanbu97** [comment]
For simplicity, maybe a channel and spawned OraclePool can be introduced. But the performance will be limited to single thread(or multi by mpmc and multiple spawned). Do you have any good idea?

**Comment by greenhat** [comment]
> For simplicity, maybe a channel and spawned OraclePool can be introduced. But the performance will be limited to single thread(or multi by mpmc and multiple spawned). Do you have any good idea?

Oh, it sounds way too complicated. It's essentially a bunch of parameters of simple types used to query the node. I mean, I'm not even sure that we need `OraclePool` to keep those "scans" together. I believe we can pass them directly to the interested parties. Also, `*Scan` types are not set in stone and can be altered if needed.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
